"""add records and reminders tables

Revision ID: 340abb68f6e7
Revises: 6aa2575da496
Create Date: 2026-03-20 12:02:41.485349
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '340abb68f6e7'
down_revision = '6aa2575da496'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """执行数据库升级。"""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_type', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('weight_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_records_pet_id'), 'pet_records', ['pet_id'], unique=False)
    op.create_table('record_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['pet_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_images_record_id'), 'record_images', ['record_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=100), nullable=False),
    sa.Column('cycle_days', sa.Integer(), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=False),
    sa.Column('next_reminder_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_id'], ['pet_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_pet_id'), 'reminders', ['pet_id'], unique=False)
    op.create_index(op.f('ix_reminders_record_id'), 'reminders', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """执行数据库回滚。"""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_record_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_pet_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_record_images_record_id'), table_name='record_images')
    op.drop_table('record_images')
    op.drop_index(op.f('ix_pet_records_pet_id'), table_name='pet_records')
    op.drop_table('pet_records')
    # ### end Alembic commands ###

