"""create users and pets tables

Revision ID: 6aa2575da496
Revises: 
Create Date: 2026-03-20 11:57:14.971533
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '6aa2575da496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """执行数据库升级。"""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('user_type', sa.String(length=20), server_default='normal', nullable=False),
    sa.Column('vip_expire_time', sa.DateTime(), nullable=True),
    sa.Column('ai_analysis_used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("user_type IN ('normal', 'vip')", name='ck_users_user_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_table('pets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('species', sa.String(length=20), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('approximate_age', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('is_neutered', sa.Boolean(), nullable=True),
    sa.Column('fur_color', sa.String(length=50), nullable=True),
    sa.Column('adoption_date', sa.Date(), nullable=True),
    sa.Column('allergy_history', sa.Text(), nullable=True),
    sa.Column('chronic_disease', sa.Text(), nullable=True),
    sa.Column('current_food_brand', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_user_id'), 'pets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """执行数据库回滚。"""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pets_user_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
